version: '3'

includes:
  task2:
    taskfile: ../task2/Taskfile.yml
    dir: ../task2


tasks:
  up:
    desc: "Description up Task1"
    summary: "Summary up Task1"
    cmds:
    - pwd
    - echo "task1 up!"

  all:
    desc: "Run up in Task1 and Task2"
    summary: "Summary of all"
    cmds:
    - task: up
    - task: task2:up

  sh:
    desc: "Start a shell somewhere?"
    cmds:
      - echo {{.CLI_ARGS}}
